### ISSUE TITLE
Any tips on fixing this error?

### ISSUE THREAD

**Issue by kingram6865** [rfrail3/tuptime#59]
```
$ sudo apt install tuptime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  distro-info libraspberrypi0
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  tuptime
0 upgraded, 1 newly installed, 0 to remove and 87 not upgraded.
Need to get 28.9 kB of archives.
After this operation, 101 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 tuptime all 4.1.0 [28.9 kB]
Fetched 28.9 kB in 1s (57.0 kB/s) 
Selecting previously unselected package tuptime.
(Reading database ... 223997 files and directories currently installed.)
Preparing to unpack .../archives/tuptime_4.1.0_all.deb ...
Unpacking tuptime (4.1.0) ...
Setting up tuptime (4.1.0) ...
Adding tuptime user ...
Traceback (most recent call last):
  File "/usr/bin/tuptime", line 20, in <module>
    import sys, os, argparse, locale, platform, signal, logging, sqlite3, time
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
dpkg: error processing package tuptime (--configure):
 installed tuptime package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.11) ...
Errors were encountered while processing:
 tuptime
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rfrail3** [comment]
At first, after a quick test over a new fresh install, the same Ubuntu Focal 20.04 release uses python3.8 and in your case, the version is 3.7:

```
root@ip:/home/ubuntu# apt install tuptime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  tuptime
0 upgraded, 1 newly installed, 0 to remove and 100 not upgraded.
Need to get 28.9 kB of archives.
After this operation, 101 kB of additional disk space will be used.
Get:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 tuptime all 4.1.0 [28.9 kB]
Fetched 28.9 kB in 0s (723 kB/s)
Selecting previously unselected package tuptime.
(Reading database ... 60149 files and directories curently installed.)
Preparing to unpack .../archives/tuptime_4.1.0_all.deb ...
Unpacking tuptime (4.1.0) ...
Setting up tuptime (4.1.0) ...
Adding tuptime user ...
Created symlink /etc/systemd/system/multi-user.target.wants/tuptime.service → /lib/systemd/system/tuptime.service.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.6) ...
root@ip:/home/ubuntu# tuptime -V
tuptime version 4.1.0
```
Could you try to make `apt update` and `apt install python3 tuptime` to see if that solves the issue? It seems that the Python sqlite module isn't working as expected.

**Comment by kingram6865** [comment]
> Could you try to make apt update and apt install python3 tuptime to see if that solves the issue? It seems that the Python sqlite module isn't working as expected.

That's what I did before making the issue .

**Comment by rfrail3** [comment]
Does a simple import of the module produce any error?

`python3 -c "import sqlite3"`

**Comment by kingram6865** [comment]
> python3 -c "import sqlite3"

$ python3 -c "import sqlite3"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by kingram6865** [comment]
I am recompiling Python 3.7. Will see if that fixes it.

**Comment by kingram6865** [comment]
Ok. Recompile fixed the problem, whatever it was.
Everything's working.
